name: 'Package Version IDs'
description: 'Find ids for package versions based on the version name'
inputs:
  version:
    description: 'A regular expression that is matched against the name of the version'
    required: true

  token:
    description: >
      Token with the necessary scopes to read package versions. 
      Defaults to github.token scoped to the repo running the action.
    required: false
    default: ${{ github.token }}

outputs:
  ids:
    description: 'Comma separated list of ids for the given version'
runs:
  using: 'node16'
  main: 'dist/index.js'
